In [ ]:
import pandas as pd

In [ ]:
#Exercicio 1 - Salários SF

In [ ]:
sal = pd.read_csv("Salaries.csv") #leitura do arquivo

In [ ]:
sal.head() #encontrar os dados iniciais

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [ ]:
len(sal) #numero de linhas

148654

In [ ]:
sal.info() #numero de entradas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [ ]:
sal['BasePay'].mean() #salarios medios

np.float64(66325.4488404877)

In [ ]:
sal['OvertimePay'].max()#encontra o maior valor

245131.88

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'] #JOSEPH DRISCOLL Maiusculo, cargo

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL'] ['TotalPayBenefits']#salario dele

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [ ]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()] #juntando tudo, quem mais ganha passa um vetor do salario, depois iguala ele a um vetor do total de beneficios, o que retorna os booleanos, e concatena mais uma vez para devolver o nome.

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [ ]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()] #mesma coisa para encontrar o minimo

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [ ]:
sal.groupby('Year').mean(numeric_only=True)['BasePay'] #alteração do código do professor - media anual, passa os numeros.

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [ ]:
sal['JobTitle'].nunique() #titulos unicos

2159

In [ ]:
sal['JobTitle'].value_counts().head()#emprego mais comuns - numero de frequencia

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [ ]:
sum(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1) #ocorrencia de trabalho em 2013

202

In [ ]:
def chefe_cargo(cargo):
    if 'chief' in cargo.lower():
        return True
    else:
        return False #palavra chefe em seu cargo precisa da função, contabilizando isso

In [ ]:
sum(sal['JobTitle'].apply(lambda x: chefe_cargo(x))) # lambda como função rápida

627

In [ ]:
sal['tam'] = sal['JobTitle'].apply(len) #existe correlação entre o comprimento da sequencia do titulo do trabalho e o salario? - não.

In [ ]:
sal[['tam', 'TotalPayBenefits']].corr() #correlaciona as duas colunas

                       tam  TotalPayBenefits
tam               1.000000         -0.036878
TotalPayBenefits -0.036878          1.000000

In [ ]:
#Exercício 2 - Soluções para Compras de Ecomerce

In [35]:
ecom = pd.read_csv('Ecommerce Purchases.txt')

In [36]:
ecom.head() #novamente, igual ao anterior

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [38]:
ecom.shape #tamanho(L e C)

(10000, 14)

In [39]:
ecom['Purchase Price'].mean() #preço medio

np.float64(50.347302)

In [40]:
ecom['Purchase Price'].max() #maior valor

99.99

In [41]:
ecom['Purchase Price'].min() #menor valor

0.0

In [43]:
ecom[ecom['Language'] == 'en'].shape #lingua escolhida no site - Inglês.

(1098, 14)

In [46]:
ecom[ecom['Job'] == 'Lawyer'].shape #cargo advogado, em ingles

(30, 14)

In [47]:
ecom['AM or PM'].value_counts() #Compras durante o dia ou noite

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

In [48]:
ecom['Job'].value_counts().head() #titulos comuns, igual ao ex anterior

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Designer, jewellery                  27
Name: count, dtype: int64

In [51]:
ecom[ecom['Lot'] == '90 WT']['Purchase Price'] #pesquisa pela regiao definida

513    75.1
Name: Purchase Price, dtype: float64

In [52]:
ecom[ecom['Credit Card']==4926535242672853]['Email'] #email da pessoa com esse cartao

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [53]:
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95)].shape #Fornecedor american Express, filtro duplo com & servindo como parte da "função", assim como na tabala verdade, portas lógicas...

(39, 14)

In [54]:
sum(ecom['CC Exp Date'].apply(lambda year : year[3:]) == '25') #cartoes que expiram em 2025

1033

In [55]:
ecom['Email'].apply(lambda prov: prov.split('@')[1]).value_counts().iloc[:5] #emails comuns

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64